version: "3.8"
services:

  api-gw:
    image: alpapad/api-gw:0.0.1-SNAPSHOT
    build:
      context: api-gw
      dockerfile: Dockerfile
    ports:
      - 8443:8443
  envoy-to-grpc:
    image: alpapad/envoy-proxy:0.0.1-SNAPSHOT
    build:
      context: envoy
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  spring-grpc:
    image: alpapad/spring-grpc:0.0.1-SNAPSHOT
    ports:
       - 9090:9090

